when:
  - event: push
    branch: main
  - event: tag
    ref: refs/tags/v*

variables:
  - &dotnet_image "mcr.microsoft.com/dotnet/sdk:10.0-preview"
  - &docker_image "woodpeckerci/plugin-docker-buildx:5"

steps:
  # Build and test
  - name: build-and-test
    image: *dotnet_image
    commands:
      - dotnet restore
      - dotnet build -c Release --no-restore
      - dotnet test -c Release --no-build --no-restore

  # Version bump with cog (only on push to main, not tags)
  - name: version-bump
    image: alpine:latest
    when:
      - event: push
        branch: main
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
      GIT_AUTHOR_NAME: "Woodpecker CI"
      GIT_AUTHOR_EMAIL: "ci@barrywalker.io"
      GIT_COMMITTER_NAME: "Woodpecker CI"
      GIT_COMMITTER_EMAIL: "ci@barrywalker.io"
    commands:
      - apk add --no-cache git curl bash
      # Install cocogitto
      - curl -sSL https://github.com/cocogitto/cocogitto/releases/download/6.2.0/cocogitto-6.2.0-aarch64-unknown-linux-musl.tar.gz | tar xz -C /usr/local/bin
      # Configure git
      - git config --global user.email "ci@barrywalker.io"
      - git config --global user.name "Woodpecker CI"
      - git config --global --add safe.directory $CI_WORKSPACE
      # Set up git credentials for push
      - git remote set-url origin https://x-access-token:$GITHUB_TOKEN@github.com/barryw/sim6502.git
      # Bump version based on conventional commits
      - |
        if cog bump --auto; then
          echo "Version bumped successfully"
          git push origin main --tags
        else
          echo "No version bump needed or already at correct version"
        fi

  # Build and push Docker image on tags
  - name: docker-build-push
    image: *docker_image
    privileged: true
    when:
      - event: tag
        ref: refs/tags/v*
    settings:
      registry: ghcr.io
      repo: ghcr.io/barryw/sim6502
      tags:
        - latest
        - "${CI_COMMIT_TAG##v}"
      username: barryw
      password:
        from_secret: github_token
      platforms:
        - linux/amd64
        - linux/arm64

  # Build and push latest on main push
  - name: docker-build-push-latest
    image: *docker_image
    privileged: true
    when:
      - event: push
        branch: main
    settings:
      registry: ghcr.io
      repo: ghcr.io/barryw/sim6502
      tags:
        - latest
        - "sha-${CI_COMMIT_SHA:0:8}"
      username: barryw
      password:
        from_secret: github_token
      platforms:
        - linux/amd64
        - linux/arm64
