when:
  - event: push
    branch: main
  - event: tag

labels:
  platform: linux/amd64

steps:
  # Build and test
  - name: build-and-test
    image: mcr.microsoft.com/dotnet/sdk:10.0
    commands:
      - dotnet restore
      - dotnet build -c Release --no-restore
      - dotnet test -c Release --no-build --no-restore

  # Version bump with cog (only on push to main, not tags)
  - name: version-bump
    image: alpine:latest
    when:
      - event: push
        branch: main
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
      GIT_AUTHOR_NAME: "Woodpecker CI"
      GIT_AUTHOR_EMAIL: "ci@barrywalker.io"
      GIT_COMMITTER_NAME: "Woodpecker CI"
      GIT_COMMITTER_EMAIL: "ci@barrywalker.io"
    commands:
      - apk add --no-cache git curl bash tar
      - curl -sSL https://github.com/cocogitto/cocogitto/releases/download/6.2.0/cocogitto-6.2.0-x86_64-unknown-linux-musl.tar.gz | tar xz -C /tmp
      - cp /tmp/x86_64-unknown-linux-musl/cog /usr/local/bin/cog
      - chmod +x /usr/local/bin/cog
      - cog --version
      - git config --global user.email "ci@barrywalker.io"
      - git config --global user.name "Woodpecker CI"
      - git config --global --add safe.directory $CI_WORKSPACE
      - git remote set-url origin https://x-access-token:$GITHUB_TOKEN@github.com/barryw/sim6502.git
      - git fetch --tags --unshallow || git fetch --tags
      - cog get-version || echo "No version found"
      - cog bump --auto && git push origin main --tags || echo "No version bump needed"

  # Build and push Docker image on tags using kaniko
  - name: docker-build-push
    image: gcr.io/kaniko-project/executor:debug
    when:
      - event: tag
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    commands:
      - mkdir -p /kaniko/.docker
      - echo "{\"auths\":{\"ghcr.io\":{\"username\":\"barryw\",\"password\":\"$GITHUB_TOKEN\"}}}" > /kaniko/.docker/config.json
      - /kaniko/executor --context $CI_WORKSPACE --dockerfile $CI_WORKSPACE/Dockerfile --destination ghcr.io/barryw/sim6502:latest --destination "ghcr.io/barryw/sim6502:$CI_COMMIT_TAG" --cache=true

  # Build and push latest on main push using kaniko
  - name: docker-build-push-latest
    image: gcr.io/kaniko-project/executor:debug
    when:
      - event: push
        branch: main
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    commands:
      - mkdir -p /kaniko/.docker
      - echo "{\"auths\":{\"ghcr.io\":{\"username\":\"barryw\",\"password\":\"$GITHUB_TOKEN\"}}}" > /kaniko/.docker/config.json
      - /kaniko/executor --context $CI_WORKSPACE --dockerfile $CI_WORKSPACE/Dockerfile --destination ghcr.io/barryw/sim6502:latest --destination "ghcr.io/barryw/sim6502:sha-${CI_COMMIT_SHA:0:8}" --cache=true
