when:
  - event: push
    branch: main

labels:
  platform: linux/amd64

steps:
  - name: build-and-test
    image: mcr.microsoft.com/dotnet/sdk:10.0
    commands:
      - dotnet restore
      - dotnet build -c Release
      - dotnet test -c Release

  - name: release
    image: alpine
    when:
      - evaluate: 'CI_COMMIT_MESSAGE not contains "chore(release):"'
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    commands:
      - apk add --no-cache git curl perl
      - curl -sSL https://github.com/cocogitto/cocogitto/releases/latest/download/cocogitto-6.5.0-x86_64-unknown-linux-musl.tar.gz | tar xz
      - mv cog /usr/local/bin/
      - git config --global user.name "Woodpecker CI"
      - git config --global user.email "ci@woodpecker.local"
      - git config --global --add safe.directory "$CI_WORKSPACE"
      - git fetch --unshallow --tags || git fetch --tags
      - git remote set-url origin "https://x-access-token:$GITHUB_TOKEN@github.com/barryw/sim6502.git"
      - |
        if cog bump --auto --dry-run 2>&1 | grep -qE "(No conventional commits|already on)"; then
          echo "No version bump needed"
          exit 0
        fi
      - cog bump --auto
      - git push origin HEAD:main --tags
    depends_on: [build-and-test]

  - name: docker
    image: gcr.io/kaniko-project/executor:debug
    when:
      - evaluate: 'CI_COMMIT_MESSAGE not contains "chore(release):"'
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    commands:
      - |
        # Get version from latest tag (cog just created it)
        VERSION=$(git describe --tags --abbrev=0 2>/dev/null | sed 's/^v//' || echo "0.0.0")
        echo "Building Docker image: $VERSION"
        mkdir -p /kaniko/.docker
        echo "{\"auths\":{\"ghcr.io\":{\"username\":\"barryw\",\"password\":\"$GITHUB_TOKEN\"}}}" > /kaniko/.docker/config.json
        /kaniko/executor \
          --context="$CI_WORKSPACE" \
          --dockerfile="$CI_WORKSPACE/Dockerfile" \
          --destination="ghcr.io/barryw/sim6502:v$VERSION" \
          --destination="ghcr.io/barryw/sim6502:latest"
    depends_on: [release]
