when:
  - event: push
    branch: main
    evaluate: 'CI_COMMIT_MESSAGE not contains "chore(version):"'

labels:
  platform: linux/amd64

steps:
  - name: build-and-test
    image: mcr.microsoft.com/dotnet/sdk:10.0
    commands:
      - dotnet restore
      - dotnet build -c Release
      - dotnet test -c Release --no-build

  - name: release
    image: alpine
    when:
      - evaluate: 'CI_COMMIT_MESSAGE not contains "chore(version):"'
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    commands:
      - apk add --no-cache git curl perl
      - curl -sSL https://github.com/cocogitto/cocogitto/releases/latest/download/cocogitto-6.5.0-x86_64-unknown-linux-musl.tar.gz | tar xz -C /tmp
      - mv /tmp/x86_64-unknown-linux-musl/cog /usr/local/bin/
      - git config --global user.name "Woodpecker CI"
      - git config --global user.email "ci@woodpecker.local"
      - git config --global --add safe.directory "$CI_WORKSPACE"
      - git fetch --unshallow --tags || git fetch --tags
      - git remote set-url origin "https://x-access-token:$GITHUB_TOKEN@github.com/barryw/sim6502.git"
      - |
        if cog bump --auto --dry-run 2>&1 | grep -qE "(No conventional commits|already on)"; then
          echo "No version bump needed"
          exit 0
        fi
      - cog bump --auto
      - git push origin HEAD:main --tags
      - |
        # Create GitHub release with changelog
        apk add --no-cache github-cli
        VERSION=$(git describe --tags --abbrev=0)
        PREV_VERSION=$(git describe --tags --abbrev=0 $VERSION^ 2>/dev/null || echo "")
        if [ -n "$PREV_VERSION" ]; then
          NOTES=$(git log --pretty=format:"- %s" $PREV_VERSION..$VERSION^)
        else
          NOTES=$(git log --pretty=format:"- %s" $VERSION^)
        fi
        gh release create "$VERSION" --title "$VERSION" --notes "$NOTES"
        echo "${VERSION#v}" > "$CI_WORKSPACE/VERSION"
    depends_on: [build-and-test]

  - name: build-binaries
    image: mcr.microsoft.com/dotnet/sdk:10.0
    when:
      - evaluate: 'CI_COMMIT_MESSAGE not contains "chore(version):"'
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    commands:
      - |
        # Only run if the release step produced a VERSION file
        if [ ! -f "$CI_WORKSPACE/VERSION" ]; then
          echo "No new release — skipping binary build"
          exit 0
        fi
        VERSION="v$(cat "$CI_WORKSPACE/VERSION")"
        echo "Building binaries for $VERSION"
      - |
        # Install gh CLI and zip
        apt-get update -qq && apt-get install -y -qq gh zip > /dev/null 2>&1
      - |
        VERSION="v$(cat "$CI_WORKSPACE/VERSION")"
        NUMERIC_VERSION=$(cat "$CI_WORKSPACE/VERSION")
        mkdir -p release-assets

        # Update version in csproj
        sed -i "s|<Version>.*</Version>|<Version>$NUMERIC_VERSION</Version>|" sim6502/sim6502.csproj
        sed -i "s|<AssemblyVersion>.*</AssemblyVersion>|<AssemblyVersion>$NUMERIC_VERSION.0</AssemblyVersion>|" sim6502/sim6502.csproj
        sed -i "s|<FileVersion>.*</FileVersion>|<FileVersion>$NUMERIC_VERSION.0</FileVersion>|" sim6502/sim6502.csproj

        for RID in linux-x64 linux-arm64 osx-x64 osx-arm64 win-x64 win-arm64; do
          echo "--- Publishing $RID ---"
          dotnet publish sim6502/sim6502.csproj -c Release -r "$RID" -p:PublishSingleFile=true -o "publish/$RID"

          # Determine binary name
          case "$RID" in
            win-*) BINARY="sim6502-${RID}.exe"; SRC="publish/$RID/Sim6502TestRunner.exe" ;;
            *)     BINARY="sim6502-${RID}";     SRC="publish/$RID/Sim6502TestRunner" ;;
          esac

          # Stage binary, generate SHA, zip together
          STAGING="staging/$RID"
          mkdir -p "$STAGING"
          cp "$SRC" "$STAGING/$BINARY"
          cd "$STAGING"
          sha256sum "$BINARY" > "${BINARY}.sha256"
          zip "../../release-assets/sim6502-${RID}.zip" "$BINARY" "${BINARY}.sha256"
          cd ../..
        done

        # Upload zip files to the GitHub release
        gh release upload "$VERSION" ./release-assets/*.zip --clobber
    depends_on: [release]

  - name: docker
    image: gcr.io/kaniko-project/executor:debug
    when:
      - evaluate: 'CI_COMMIT_MESSAGE not contains "chore(version):"'
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    commands:
      - VERSION=$(wget -qO- https://api.github.com/repos/barryw/sim6502/releases/latest | sed -n 's/.*"tag_name".*"v\([^"]*\)".*/\1/p')
      - echo "Building version $VERSION"
      # Update version in csproj before building (in case post_bump_hook didn't work)
      - sed -i "s|<Version>.*</Version>|<Version>$VERSION</Version>|" sim6502/sim6502.csproj
      - sed -i "s|<AssemblyVersion>.*</AssemblyVersion>|<AssemblyVersion>$VERSION.0</AssemblyVersion>|" sim6502/sim6502.csproj
      - sed -i "s|<FileVersion>.*</FileVersion>|<FileVersion>$VERSION.0</FileVersion>|" sim6502/sim6502.csproj
      - mkdir -p /kaniko/.docker
      - echo "{\"auths\":{\"ghcr.io\":{\"username\":\"barryw\",\"password\":\"$GITHUB_TOKEN\"}}}" > /kaniko/.docker/config.json
      - /kaniko/executor --context="$CI_WORKSPACE" --dockerfile="$CI_WORKSPACE/Dockerfile" --destination="ghcr.io/barryw/sim6502:v$VERSION" --destination="ghcr.io/barryw/sim6502:latest"
    depends_on: [release]
